# Go parameters
GOCMD=go
GOBUILD=$(GOCMD) build
GOCLEAN=$(GOCMD) clean
GOTEST=$(GOCMD) test
GOGET=$(GOCMD) get
BINARY_NAME=myapp
VERSION=1.0.0

all: test build
build: 
	$(GOBUILD) -o $(BINARY_NAME) -v
test: 
	$(GOTEST) -v ./...
clean: 
	$(GOCLEAN)
	rm -f $(BINARY_NAME)
run:
	$(GOBUILD) -o $(BINARY_NAME) -v ./...
	./$(BINARY_NAME)
deps:
	$(GOGET) github.com/markbates/goth
	$(GOGET) github.com/gorilla/mux
	$(GOGET) github.com/go-sql-driver/mysql
	$(GOGET) github.com/gorilla/sessions
	$(GOGET) github.com/joho/godotenv
	$(GOGET) github.com/stretchr/testify/assert
	$(GOGET) github.com/dgrijalva/jwt-go
